---
id: picoruby-to-twitch-en
base_name: picoruby-to-twitch-en
tags: []
presentation_date:
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri:
author:
  markup_language: :rd
  name: Joschka Schulz
  email: Horstyschulz@gmail.com
  rubygems_user:
  slideshare_user:
  speaker_deck_user:
